# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_item_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='container',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
